name: Documentation
on:
  push:
    branches:
      - develop
      - feature/*
      - main/*
      - bugfix/*
    paths:
      - docs/**
  pull_request:
    types: [opened, reopened, synchronize]

env:
  PYTHONPATH: ${GITHUB_WORKSPACE}/src

jobs:
  create_documentation:
    runs-on: ubuntu-latest
    name: Deploy documentation

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.7'

    - name: Install ubuntu dependencies
      run: |
        echo "Install ubuntu dependencies (if any)"

    - name: Install (upgrade) dependencies
      run: |
        python -m pip install --upgrade pip sphinx sphinx-gallery sphinx_rtd_theme

    - name: Build documentation
      run: |
        ./.github/scripts/build-documentation
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: documentation
        path: artifact/documentation
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: documentation_warnings.log
        path: artifact/doc_warnings.log
        if-no-files-found: ignore

