name: Test
on:
  pull_request:
    branches:
      - develop
      - doc-update
  push:
    branches:
      - develop
      - doc-update
  workflow_dispatch:
    branches:
      - develop
      - doc-update
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install conda
        run:  .github/scripts/install-conda.sh
      - name: Test
        run:  .github/scripts/test.sh
      - name: Format Check
        run:  .github/scripts/format-check.sh
      - name: Docs Link Check
        run: .github/scripts/link-check.sh
